sfm:
    resource: "@SFMPicmntBundle/Controller/IndexController.php"
    type:     annotation
  
fos_user_security:
    resource: "@SFMUserBundle/Resources/config/routing/security.xml"

fos_user_user:
    resource: "@SFMUserBundle/Resources/config/routing/user.xml"
    prefix: /user
